version: "3.8"

services:
  db:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: target_clients
      POSTGRES_USER: targetuser
      POSTGRES_PASSWORD: targetpassword
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data:
